version: "3.5"

services:
  alerta-web:
    container_name: "alerta-web"
    image: "hayk96/alerta-web:latest"
    environment:
      DATABASE_URL: "postgres://postgres:changeme@postgresql:5432/alerta"
      ADMIN_USERS: "admin"
      ADMIN_PASSWORD: "admin"
      AUTH_REQUIRED: "True"
      SIGNUP_ENABLED: "False"
      ADMIN_KEY: "1111-2222-3333-4444"
      ALERTA_API_KEY: "1111-2222-3333-4444"
      INSTALL_PLUGINS:  "prometheus,normalise,enhance"
      ALERTMANAGER_API_URL: "http://your-alertmanager.com"
      ALERTMANAGER_SILENCE_FROM_ACK: "True"
    ports:
      - "8080:8080"
    depends_on:
      - "postgresql"
  postgresql:
    container_name: "alerta-db"
    image: "bitnami/postgresql:11.14.0-debian-10-r28"
    environment:
      POSTGRES_DB: "alerta"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "changeme"
      POSTGRES_POSTGRES_PASSWORD: "changeme"