apiVersion: v2
appVersion: "8.7.0"
description: A Helm chart for Kubernetes
name: alerta
version: 0.4.0
home: https://github.com/hayk96/alerta-web
dependencies:
  - name: postgresql
    version: "10.16.2"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
sources:
  - https://github.com/alerta/alerta
  - https://github.com/alerta/alerta-webui
maintainers:
  - name: Hayk Davtyan
    url: https://github.com/hayk96
keywords:
  - monitoring
  - alerting
