replicaCount: 1

image:
  repository: hayk96/alerta-web
  tag: 8.7.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
  # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
  # ingressClassName: nginx
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - alerta.example.com
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 200
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 128Mi

alertaAdminPassword: ALERTA_ADMIN_PASSWORD
alertaAdminUsers:
  - admin

alertaAdminKey: ALERTA_ADMIN_KEY
alertaApiKey:   ALERTA_ADMIN_KEY

alertaInstallPlugins:
  - prometheus
  - normalise
  - enhance

# ref: http://docs.alerta.io/en/latest/configuration.html
alertaConfig:
  DEBUG: "False"
  AUTH_REQUIRED: "True"
  SIGNUP_ENABLED: "False"
  DELETE_EXPIRED_AFTER: 60
  DELETE_INFO_AFTER: 60
  COLUMNS: "['severity', 'status', 'lastReceiveTime', 'environment', 'service', 'resource', 'event', 'value', 'text']"
  ACTIONS: "['createIssue', 'updateIssue']"
  PLUGINS: "['prometheus', 'normalise', 'enhance']"
  ALERTMANAGER_API_URL: '"http://prometheus-alertmanager.svc"'
  ALERTMANAGER_SILENCE_FROM_ACK: "True"
  LOG_HANDLERS: "['console']"
  COLOR_MAP: "{
  'severity': {
    'security': '#000000',
    'critical': 'red',
    'major' : '#F89407',
    'minor' : '#f8bc07',
    'warning': '#1E90FF',
    'indeterminate': '#a32cf2',
    'informational': 'green',
    'ok': '#00CC00',
    'normal': '#0aab78',
    'unknown': 'silver'
  },
  'text': 'white'
  }"

postgresql:
  enabled: true
  postgresqlDatabase: alerta
  postgresqlUsername: alerta
  postgresqlPassword: PG_ALERTA_PASSWORD
  persistence:
    enabled: true
    size: 1Gi
